@startuml

left to right direction

skinparam linetype ortho

package "Model" {
	class Usuarie {
	}
	class Cliente {
	}
	class Administrador {
	}
	class Auxiliar {
	}
	class Repartidor {
	}
	class Pedido {
	}
	class Producto {
	}
	class Menu {
	}
	class Descuento {
	}
	class Establecimiento {
	}
}

package "View" {
	class vLogin
	class vMenuCliente
	class vMenuTrabajador
	class vPedidor
	class vConsultarPedidos
	class vModificarDatos
}

package "Controller" {
	class ADUsuarie {
	}
	class ADProducto {
	}
	class ADPedido {
	}
	class ADMenu{
	}
	class ADDescuento {
	}
	class ADEstablecimiento {
	}
	package "Interfaces" {
		interface Usuariable {
			login()
			modificarDatos()
			findUsuarie()
			listarUsuaries()
		}
		interface Descontable {
			addDescuento()
			modDescuento()
			rmDescuento()
			findDescuento()
			listarDescuentos()
		}
		interface Pedible {
			addPedido()
			modPedido()
			findPedido()
			listarPedidos()
		}
		interface Establecimientable {
			addEstableciemiento()
			modEstableciemiento()
			rmEstableciemiento()
			findEstablecimiento()
			listarEstablecimientos()
		}
		interface Menuable {
			addMenu()
			rmMenu()
			findMenu()
			listarMenus()
		}
		interface Productable {
			addProducto()
			modProducto()
			rmProducto()
			findProducto()
			listarProductos()
		}
	}

	package "Factorias" {
		class UsuarieFactory {
			getUsuarie()
		}
		class ProductoFactory {
			getProducto()
		}
		class PedidoFactory {
			getPedido()
		}
		class MenuFactory {
			getMenu()
		}
		class DescuentoFactory {
			getDescuento()
		}
		class EstablecimientoFactory {
			getEstablecimiento()
		}
	}
}

package "MySql" {
		class Usuarie {
		}
		class Pedido {
		}
		class Producto {
		}
		class Menu {
		}
		class Descuento {
		}
		class Establecimiento {
		}
}

ADUsuarie ..> Usuariable
ADProducto ..> Productable
ADPedido ..> Pedible
ADMenu ..> Menuable
ADDescuento ..> Descontable
ADEstablecimiento ..> Establecimientable

Usuariable -- UsuarieFactory
Productable -- ProductoFactory
Pedible -- PedidoFactory
Menuable -- MenuFactory
Descontable -- DescuentoFactory
Establecimientable -- EstablecimientoFactory

@enduml
